---
title: "PDAC immune networks"
author: "Marc Elosua-Bayes"
date: "5/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

In this Rmarkdown document we will divide the spots into cancer and non-cancer and then check if there is immune cell enrichment in one of the 2 bins.
```{r setup, include=FALSE}
library(dplyr)
library(NMF)
library(purrr)
library(tibble)
library(ggplot2)
library(Matrix)
library(Seurat)
library(Spaniel)
library(SPOTlight)
library(flextable)
source("utils/bin.r")
source("utils/spatial_plot_spaniel.R")
```

Paths
```{r}
#### Setting vrs ####
tech <- "sc"
tissue <- "pdac_unpaired"
dwn_smplng <- "both"
org <- "hs"
source("misc/paths_vrs.R")

clust_vr <- "cell_type_specific"
cl_n <- 100
method <- "nsNMF"
transf <- "uv"
hvg <- 3000
ntop <- NULL
FC <- "all"
pct1 <- "all"

id_nmf <- sprintf("cln-%s_transf-%s_method-%s_hvg-%s_FC-%s_pct1-%s", 
                  cl_n, transf, method, hvg, FC, pct1)


library(RColorBrewer)
n <- 60
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector  <-  unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))


# sample dictionary
sample_dict <- list()
sample_dict[["GSM3036911"]] = "PDAC-A ST1"
sample_dict[["GSM3405534"]] = "PDAC-B ST1"
sample_dict[["GSM4100721"]] = "PDAC-A ST2"
sample_dict[["GSM4100722"]] = "PDAC-A ST3"
sample_dict[["GSM4100723"]] = "PDAC-B ST2"
sample_dict[["GSM4100724"]] = "PDAC-B ST3"

pdac_a_smpl <- c("GSM3036911", "GSM4100721", "GSM4100722")
pdac_b_smpl <- c("GSM3405534", "GSM4100723", "GSM4100724")
pdac_smpl <- c(pdac_a_smpl, pdac_b_smpl)

dir.create(path = sprintf("%s/%s", an_pdac, plt_dir), showWarnings = FALSE, recursive = TRUE)
dir.create(path = sprintf("%s/%s", an_pdac, robj_dir), showWarnings = FALSE, recursive = TRUE)
```


## Load data
### scRNAseq data
```{r}
# ica_se <- readRDS("data/immune_cancer_atlas/pancreas_new_celltypes_100.rds")
# ica_se <- ica_se[, !ica_se$specific_cell_type %in% c("Macro_2", "Macro_3")]
update_annot <- readr::read_csv(
  "data/immune_cancer_atlas/TICAtlas_metadata.csv"
  ) %>% dplyr::rename(barcode = X1)
```

### Deconvolution matrices
Load the immune cell atlas matrices
```{r}
decon_mtrx_dir <- sprintf("%s/%s", an_pdac, robj_dir)
decon_fn_ls <- list.files(path = decon_mtrx_dir,
                       pattern = "^decon_mtrx_ica-integration_specific")[1:6]



immune_decon_mtrx_ls <- lapply(decon_fn_ls, function(fn) {
  path_str <- paste(decon_mtrx_dir, fn, sep = "/")
  decon_mtrx <- readRDS(file = path_str)
  return(decon_mtrx)
})

names_ls <- sapply(decon_fn_ls, USE.NAMES = FALSE, function(i) stringr::str_split(string = i, pattern = "_")[[1]][5])

names(immune_decon_mtrx_ls) <- names_ls

```

### Color dataframe
Cell type specific color
```{r}
cell_types_plt <- sort(unique(update_annot$cell_type))

pdac_plt_names <- data.frame(df_name = gsub(pattern = "[[:punct:]]|[[:blank:]]", ".",
                                            x = cell_types_plt,
                                            perl = TRUE), 
                           plt_name = cell_types_plt,
                           col_ct = col_vector[seq_len(length(cell_types_plt))])

```

### GSM3036911 specific network
```{r}
lapply(c("GSM3036911", "GSM4100723"), function(geo) {
  decon_mtrx <- immune_decon_mtrx_ls[[geo]][[2]]
  decon_mtrx <- decon_mtrx[, colnames(decon_mtrx)[!colnames(decon_mtrx) %in% "res_ss"]]
  
  # Change to right column names
  colnames(decon_mtrx) <- gsub(pattern = "[[:punct:]]|[[:blank:]]", ".", 
                                 x = colnames(decon_mtrx), 
                                 perl = TRUE)
  new_names <- data.frame(df_name = colnames(decon_mtrx)) %>% 
    left_join(pdac_plt_names, by = "df_name") %>% 
    pull(plt_name)
  
  colnames(decon_mtrx) <- new_names
  
  
  graph_ntw <- get_spatial_interaction_graph(decon_mtrx = decon_mtrx)
  
  deg <- colSums(decon_mtrx > 0) / 10
  
  # Get color palette for difusion
  edge_importance <- E(graph_ntw)$importance
  
  # Select a continuous palette
  qual_col_pals <- brewer.pal.info[brewer.pal.info$category == 'seq',]
  # Create a color vetor
  getPalette <- colorRampPalette(brewer.pal(9, "YlOrRd"))
  # Get how many values we need
  grad_edge <- seq(0, max(edge_importance), 0.1)
  # Generate extended gradient palette dataframe
  graph_col_df <- data.frame(value = as.character(grad_edge),
                             color = getPalette(length(grad_edge)),
                             stringsAsFactors = FALSE)
  # Assign color to each edge
  color_edge <- data.frame(value = as.character(round(edge_importance, 1)), stringsAsFactors = FALSE) %>%
    dplyr::left_join(graph_col_df, by = "value") %>%
    dplyr::pull(color)
  
  # jpeg(sprintf("%s/%s/Suppl_Fig_MMM_interaction_graph_immune_arrange_%s.jpeg", 
  #              an_pdac, plt_dir, geo), 
  #     width = 750,
  #     height = 750, 
  #     # res = 600,
  #     # pointsize = 0.2,
  #     quality = 100)
  # 
  # # Open a pdf file
  # plot(graph_ntw,
  #      # Size of the edge
  #      edge.width = edge_importance,
  #      edge.color = color_edge,
  #      # Size of the buble
  #      vertex.size = deg/2,
  #      vertex.color = "#cde394",
  #      vertex.frame.color = "white",
  #      vertex.label.color = "black",
  #      vertex.label.family = "Ubuntu", # Font family of the label (e.g.“Times”, “Helvetica”)
  #      layout = layout.circle,
  #      main = sprintf("%s spatial interaction network",geo ))
  # 
  # dev.off()
  
  pdf(sprintf("%s/%s/Suppl_Fig_MMM_interaction_graph_immune_arrange_%s.pdf", 
               an_pdac, plt_dir, geo), 
      width = 9,
      height = 9)
  
  # Open a pdf file
  plot(graph_ntw,
       # Size of the edge
       edge.width = edge_importance,
       edge.color = color_edge,
       # Size of the buble
       vertex.size = deg/2,
       vertex.color = "#cde394",
       vertex.frame.color = "white",
       vertex.label.color = "black",
       vertex.label.family = "Helvetica", # Font family of the label (e.g.“Times”, “Helvetica”)
       layout = layout.circle,
       main = sprintf("%s spatial interaction network",geo ))
  
  dev.off()


})

```